name: CRAN Release Check

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

env:
  R_KEEP_PKG_SOURCE: yes
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

jobs:
  cran-check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            r: 'release'
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Setup environment and install dependencies
        run: |
          # Setup virtual display (Linux)
          if [ "$RUNNER_OS" = "Linux" ]; then
            Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
            echo "export DISPLAY=:99" >> $GITHUB_ENV
            
            # Install system dependencies
            sudo apt-get update
            sudo apt-get install -y cmake build-essential libblas-dev liblapack-dev libglpk40 libglpk-dev libglib2.0-dev libgl1-mesa-dev libglu1-mesa-dev xvfb pkg-config openjdk-11-jdk
            echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
            echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          else
            # macOS dependencies
            brew install cmake glib mesa pkg-config openjdk@11
            echo "PKG_CONFIG_PATH=$(brew --prefix glib)/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
            if [ -d "/usr/local/opt/openjdk@11/" ]; then
              echo "JAVA_HOME=/usr/local/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home" >> $GITHUB_ENV
            fi
          fi
          
          # Verify Java installation
          java -version

      - name: Install R packages
        run: |
          R -e "install.packages(c('remotes', 'rcmdcheck'))"
          R -e "remotes::install_deps(dependencies = TRUE)"
          R -e "remotes::install_cran(c('devtools', 'roxygen2', 'spelling', 'rhub'))"
          
          # Install platform-specific packages
          if [ "$RUNNER_OS" = "macOS" ]; then
            R -e "tryCatch(install.packages('rgl', type = 'source'), error = function(e) install.packages('rgl'))"
            R -e "install.packages('OpenStreetMap')"
            R -e "library(rgl)"
          fi

      - name: Build and check package
        run: |
          R -e "devtools::build()"
          Rscript scripts/cran_release_check.R

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cran-check-results-${{ matrix.os }}-${{ matrix.r }}
          path: |
            *.tar.gz
            *.zip
            build/
            check.log
            final_check.log 
